version: '3'

services:
  app:
    container_name: app
    build: .
    ports:
      - "80:80"
    restart: always
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/home/SKOI19_Register
      - /home/SKOI19_Register/node_modules
      - /home/SKOI19_Register/vendor
    depends_on:
      - mysql
  
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: /SKOI19/Database
